/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package absensi.View;

import absensi.Controller.ControllerKaryawan;
import absensi.Model.Karyawan;
import absensi.Model.TableModelKaryawan;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class FormKaryawan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormKaryawan.class.getName());
    private final ControllerKaryawan controllerKaryawan = new ControllerKaryawan();
    private TableModelKaryawan tableModel;
    /**
     * Creates new form FormKaryawan
     */
    public FormKaryawan() {
        initComponents();
        setupForm();
    }
    
    private void setupForm() {
        // Kosongkan field saat form pertama dibuka
        idTF.setText("");
        namaTF.setText("");
        jabatanTF.setText("");
        cariNamaTF.setText("");

        // Load semua data karyawan ke tabel
        refreshTabel();

        // Klik baris tabel → isi field otomatis
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                int row = jTable1.getSelectedRow();
                if (row >= 0) {
                    Karyawan k = tableModel.getKaryawanAt(row);
                    idTF.setText(String.valueOf(k.getIdKaryawan()));
                    namaTF.setText(k.getNama());
                    jabatanTF.setText(k.getJabatan());
                }
            }
        });
    }
    
    private void refreshTabel() {
        List<Karyawan> list = controllerKaryawan.getAll();
        tableModel = new TableModelKaryawan(list);
        jTable1.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idLabel = new javax.swing.JLabel();
        namaLabel = new javax.swing.JLabel();
        jabatanLable = new javax.swing.JLabel();
        idTF = new javax.swing.JTextField();
        namaTF = new javax.swing.JTextField();
        jabatanTF = new javax.swing.JTextField();
        tambahBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        hapusBtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        namaCariLabel = new javax.swing.JLabel();
        cariNamaTF = new javax.swing.JTextField();
        cariBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        idLabel.setText("Id: ");

        namaLabel.setText("Nama: ");

        jabatanLable.setText("Jabatan:");

        idTF.setText("Isi Id");
        idTF.addActionListener(this::idTFActionPerformed);

        namaTF.setText("Isi nama");

        jabatanTF.setText("Isi Jabatan");

        tambahBtn.setText("Tambah");
        tambahBtn.addActionListener(this::tambahBtnActionPerformed);

        updateBtn.setText("Update");
        updateBtn.addActionListener(this::updateBtnActionPerformed);

        hapusBtn.setText("Hapus");
        hapusBtn.addActionListener(this::hapusBtnActionPerformed);

        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(this::refreshBtnActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        namaCariLabel.setText("Nama:");

        cariNamaTF.setText("Masukkan nama");
        cariNamaTF.addActionListener(this::cariNamaTFActionPerformed);

        cariBtn.setText("Cari");
        cariBtn.addActionListener(this::cariBtnActionPerformed);

        backBtn.setText("Back");
        backBtn.addActionListener(this::backBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tambahBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(updateBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hapusBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(refreshBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(namaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jabatanLable))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(idTF)
                                    .addComponent(namaTF)
                                    .addComponent(jabatanTF, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backBtn)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(namaCariLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cariNamaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cariBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaCariLabel)
                    .addComponent(cariNamaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cariBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namaLabel)
                            .addComponent(namaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jabatanLable)
                            .addComponent(jabatanTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tambahBtn)
                            .addComponent(updateBtn)
                            .addComponent(hapusBtn)
                            .addComponent(refreshBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backBtn)
                        .addGap(27, 27, 27))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTFActionPerformed

    private void cariNamaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariNamaTFActionPerformed
        cariBtnActionPerformed(evt);
    }//GEN-LAST:event_cariNamaTFActionPerformed

    private void cariBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariBtnActionPerformed
        String keyword = cariNamaTF.getText().trim();

        if (keyword.isEmpty()) {
            // Kalau field cari kosong, tampilkan semua data
            refreshTabel();
            return;
        }

        // Filter dari list yang sudah ada
        List<Karyawan> semua = controllerKaryawan.getAll();
        List<Karyawan> hasil = new java.util.ArrayList<>();

        for (Karyawan k : semua) {
            if (k.getNama().toLowerCase().contains(keyword.toLowerCase())) {
                hasil.add(k);
            }
        }

        if (hasil.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Karyawan dengan nama \"" + keyword + "\" tidak ditemukan!",
                "Info", JOptionPane.INFORMATION_MESSAGE);
            refreshTabel(); // tampilkan semua kalau tidak ketemu
        } else {
            tableModel = new TableModelKaryawan(hasil);
            jTable1.setModel(tableModel);
        }
    }//GEN-LAST:event_cariBtnActionPerformed

    private void tambahBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBtnActionPerformed
        String inputId     = idTF.getText().trim();
        String inputNama   = namaTF.getText().trim();
        String inputJabatan = jabatanTF.getText().trim();

        // Validasi kosong
        if (inputId.isEmpty() || inputNama.isEmpty() || inputJabatan.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "ID, Nama, dan Jabatan tidak boleh kosong!",
                "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validasi ID harus angka
        int id;
        try {
            id = Integer.parseInt(inputId);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "ID harus berupa angka!",
                "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Cek ID sudah ada atau belum
        if (controllerKaryawan.getById(id) != null) {
            JOptionPane.showMessageDialog(this,
                "ID " + id + " sudah digunakan! Gunakan ID lain.",
                "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Simpan ke database
        Karyawan k = new Karyawan(id, inputNama, inputJabatan);
        boolean berhasil = controllerKaryawan.tambah(k);

        if (berhasil) {
            JOptionPane.showMessageDialog(this,
                "Karyawan berhasil ditambahkan!",
                "Berhasil", JOptionPane.INFORMATION_MESSAGE);
            bersihkanField();
            refreshTabel();
        } else {
            JOptionPane.showMessageDialog(this,
                "Gagal menambahkan karyawan!",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tambahBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        String inputId      = idTF.getText().trim();
        String inputNama    = namaTF.getText().trim();
        String inputJabatan = jabatanTF.getText().trim();

        // Validasi kosong
        if (inputId.isEmpty() || inputNama.isEmpty() || inputJabatan.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Pilih dulu data dari tabel sebelum update!",
                "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validasi ID harus angka
        int id;
        try {
            id = Integer.parseInt(inputId);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "ID tidak valid!",
                "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Konfirmasi sebelum update
        int konfirmasi = JOptionPane.showConfirmDialog(this,
            "Yakin ingin mengupdate data karyawan ID " + id + "?",
            "Konfirmasi Update", JOptionPane.YES_NO_OPTION);

        if (konfirmasi == JOptionPane.YES_OPTION) {
            Karyawan k = new Karyawan(id, inputNama, inputJabatan);
            boolean berhasil = controllerKaryawan.update(k);

            if (berhasil) {
                JOptionPane.showMessageDialog(this,
                    "Data karyawan berhasil diupdate!",
                    "Berhasil", JOptionPane.INFORMATION_MESSAGE);
                bersihkanField();
                refreshTabel();
            } else {
                JOptionPane.showMessageDialog(this,
                    "Gagal mengupdate data karyawan!",
                    "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void hapusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBtnActionPerformed
        String inputId = idTF.getText().trim();

        if (inputId.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Pilih dulu data dari tabel sebelum hapus!",
                "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int id;
        try {
            id = Integer.parseInt(inputId);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "ID tidak valid!",
                "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Konfirmasi sebelum hapus
        int konfirmasi = JOptionPane.showConfirmDialog(this,
            "Yakin ingin menghapus karyawan ID " + id + "?\n"
            + "Data absensi karyawan ini juga akan terpengaruh!",
            "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);

        if (konfirmasi == JOptionPane.YES_OPTION) {
            boolean berhasil = controllerKaryawan.hapus(id);

            if (berhasil) {
                JOptionPane.showMessageDialog(this,
                    "Karyawan berhasil dihapus!",
                    "Berhasil", JOptionPane.INFORMATION_MESSAGE);
                bersihkanField();
                refreshTabel();
            } else {
                JOptionPane.showMessageDialog(this,
                    "Gagal menghapus karyawan!\n"
                    + "Kemungkinan karyawan ini masih memiliki data absensi.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_hapusBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        bersihkanField();
        cariNamaTF.setText("");
        refreshTabel();
        JOptionPane.showMessageDialog(this,
            "Data berhasil di-refresh!",
            "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        new FormDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void bersihkanField() {
        idTF.setText("");
        namaTF.setText("");
        jabatanTF.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormKaryawan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton cariBtn;
    private javax.swing.JTextField cariNamaTF;
    private javax.swing.JButton hapusBtn;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jabatanLable;
    private javax.swing.JTextField jabatanTF;
    private javax.swing.JLabel namaCariLabel;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JTextField namaTF;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton tambahBtn;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
