/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package absensi.View;

import absensi.Model.User;
import absensi.Model.Karyawan;
import absensi.Model.Shift;
import absensi.Controller.ControllerKaryawan;
import absensi.Controller.ControllerShift;
import absensi.koneksi.Koneksi;
import java.sql.*;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author ASUS
 */
public class FormCheckInUser extends javax.swing.JFrame {
    private User userLogin;
    private ControllerKaryawan controllerKaryawan;
    private ControllerShift controllerShift;
    private javax.swing.Timer timerJam;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormCheckInUser.class.getName());

    /**
     * Creates new form FormCheckInUser
     */
    public FormCheckInUser(User user) {
        initComponents();
        
        this.userLogin = user;
        controllerKaryawan = new ControllerKaryawan();
        controllerShift = new ControllerShift();

        setLocationRelativeTo(null);
        setResizable(false);

        loadDataUser();
        loadShift();
        mulaiJam();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblTanggal = new javax.swing.JLabel();
        lblShift = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        lblJam = new javax.swing.JLabel();
        btnCheckIn = new javax.swing.JButton();
        lblNamaValue = new javax.swing.JLabel();
        lblTanggalValue = new javax.swing.JLabel();
        lblJamValue = new javax.swing.JLabel();
        comboShift = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setText("Check In Karyawan");

        lblNama.setText("Nama          :");

        lblTanggal.setText("Tanggal      :");

        lblShift.setText("Shift            :");

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(this::btnLogOutActionPerformed);

        lblJam.setText("Jam             :");

        btnCheckIn.setText("Check In");
        btnCheckIn.addActionListener(this::btnCheckInActionPerformed);

        comboShift.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblShift, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCheckIn, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(comboShift, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLogOut)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblJam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTanggal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNamaValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblTanggalValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(lblJamValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(98, 98, 98))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblTitle)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNama)
                    .addComponent(lblNamaValue))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTanggal)
                    .addComponent(lblTanggalValue))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJam)
                    .addComponent(lblJamValue))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblShift)
                    .addComponent(comboShift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnCheckIn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnLogOut)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void loadDataUser() {
        Karyawan k = controllerKaryawan.getById(userLogin.getIdKaryawan());

        if (k != null) {
            lblNamaValue.setText(k.getNama());
        }

        lblTanggalValue.setText(LocalDate.now().toString());
    }

    private void loadShift() {
        comboShift.removeAllItems();
        List<Shift> listShift = controllerShift.getAll();
        for (Shift s : listShift) {
            ((javax.swing.JComboBox) comboShift).addItem(s);
        }
    }

    private void mulaiJam() {
        timerJam = new javax.swing.Timer(1000, e -> {
            lblJamValue.setText(LocalTime.now().format(DateTimeFormatter.ofPattern("HH:mm:ss")));
        });
        timerJam.start();
    }
    
    private int getNextIdAbsensi(Connection conn) throws SQLException {
        String sql = "SELECT MAX(id_absensi) FROM tabel_absensi";
        PreparedStatement ps = conn.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            return rs.getInt(1) + 1;
        }

        return 1;
    }
    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
       if (timerJam != null) {
            timerJam.stop();
        }

        new FormLogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckInActionPerformed
        try {
            Shift shift = (Shift) comboShift.getSelectedItem();

            if (shift == null) {
                JOptionPane.showMessageDialog(this, "Shift belum dipilih!");
                return;
            }

            int idKaryawan = userLogin.getIdKaryawan();
            int idShift = shift.getId_shift();
            String tanggal = LocalDate.now().toString();
            String jam = LocalTime.now().format(DateTimeFormatter.ofPattern("HH:mm:ss"));

            String status = jam.compareTo(shift.getJam_masuk()) <= 0
                    ? "Hadir Tepat Waktu"
                    : "Terlambat";

            Connection conn = Koneksi.getKoneksi();
            int idAbsensi = getNextIdAbsensi(conn);
            
            String cekSql = "SELECT * FROM tabel_absensi WHERE fk_karyawan=? AND tanggal=?";
            PreparedStatement cek = conn.prepareStatement(cekSql);
            cek.setInt(1, idKaryawan);
            cek.setString(2, tanggal);
            ResultSet rs = cek.executeQuery();

            if (rs.next()) {
                JOptionPane.showMessageDialog(this, "Kamu sudah check-in hari ini!");
                return;
            }

            String sql = "INSERT INTO tabel_absensi (id_absensi, fk_karyawan, fk_shift, tanggal, waktu_checkin, status) VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, idAbsensi);
            ps.setInt(2, idKaryawan);
            ps.setInt(3, idShift);
            ps.setString(4, tanggal);
            ps.setString(5, jam);
            ps.setString(6, status);

            ps.executeUpdate();

            JOptionPane.showMessageDialog(this, "Check-in berhasil!\nStatus: " + status);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal check-in: " + e.getMessage());
        }
    }//GEN-LAST:event_btnCheckInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new FormCheckInUser().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckIn;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JComboBox<String> comboShift;
    private javax.swing.JLabel lblJam;
    private javax.swing.JLabel lblJamValue;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNamaValue;
    private javax.swing.JLabel lblShift;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JLabel lblTanggalValue;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
