/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package absensi.View;
import absensi.Controller.ControllerShift;
import absensi.Model.Shift;
import absensi.Model.TableModelShift;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author LENOVO
 */
public class FormShift extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormShift.class.getName());
    private final ControllerShift controllerShift = new ControllerShift();
    private TableModelShift tableModel;
    /**
     * Creates new form FormShift
     */
    public FormShift() {
        initComponents();
        setupForm();
    }
    
    private void setupForm() {
        // Kosongkan semua field
        idTF.setText("");
        namaTF.setText("");
        jamTF.setText("");
        cariNamaTF.setText("");

        // Load semua data shift ke tabel
        refreshTabel();

        // Klik baris tabel → isi field otomatis
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                int row = jTable1.getSelectedRow();
                if (row >= 0) {
                    Shift s = tableModel.getShiftAt(row);
                    idTF.setText(String.valueOf(s.getId_shift()));
                    namaTF.setText(s.getNama_shift());
                    jamTF.setText(s.getJam_masuk());
                }
            }
        });
    }
    
    private void refreshTabel() {
        List<Shift> list = controllerShift.getAll();
        tableModel = new TableModelShift(list);
        jTable1.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idLabel = new javax.swing.JLabel();
        namaLabel = new javax.swing.JLabel();
        jamLabel = new javax.swing.JLabel();
        idTF = new javax.swing.JTextField();
        namaTF = new javax.swing.JTextField();
        jamTF = new javax.swing.JTextField();
        tambahBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        hapusBtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();
        cariLabel = new javax.swing.JLabel();
        cariNamaTF = new javax.swing.JTextField();
        cariBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        idLabel.setText("Id");

        namaLabel.setText("Nama Shift");

        jamLabel.setText("Jam Masuk");

        namaTF.addActionListener(this::namaTFActionPerformed);

        tambahBtn.setText("Tambah");
        tambahBtn.addActionListener(this::tambahBtnActionPerformed);

        updateBtn.setText("Update");
        updateBtn.addActionListener(this::updateBtnActionPerformed);

        hapusBtn.setText("Hapus");
        hapusBtn.addActionListener(this::hapusBtnActionPerformed);

        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(this::refreshBtnActionPerformed);

        cariLabel.setText("Cari:");

        cariNamaTF.setText("Nama Shift");
        cariNamaTF.addActionListener(this::cariNamaTFActionPerformed);

        cariBtn.setText("Cari");
        cariBtn.addActionListener(this::cariBtnActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        backBtn.setText("Back");
        backBtn.addActionListener(this::backBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(32, 32, 32)
                                    .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(namaLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(namaTF))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jamLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jamTF)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tambahBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(updateBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hapusBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(refreshBtn))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backBtn)))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cariLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cariNamaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cariBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaLabel)
                    .addComponent(namaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jamLabel)
                    .addComponent(jamTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahBtn)
                    .addComponent(updateBtn)
                    .addComponent(hapusBtn)
                    .addComponent(refreshBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cariLabel)
                    .addComponent(cariNamaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cariBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaTFActionPerformed

    private void cariNamaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariNamaTFActionPerformed
        cariBtnActionPerformed(evt);
    }//GEN-LAST:event_cariNamaTFActionPerformed

    private void tambahBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBtnActionPerformed
        String inputId       = idTF.getText().trim();
        String inputNama     = namaTF.getText().trim();
        String inputJamMasuk = jamTF.getText().trim();

        // Validasi kosong
        if (inputId.isEmpty() || inputNama.isEmpty() || inputJamMasuk.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "ID, Nama Shift, dan Jam Masuk tidak boleh kosong!",
                "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validasi ID harus angka
        int id;
        try {
            id = Integer.parseInt(inputId);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "ID harus berupa angka!",
                "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validasi format jam HH:mm:ss
        if (!inputJamMasuk.matches("^([01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d$")) {
            JOptionPane.showMessageDialog(this,
                "Format jam masuk salah!\nGunakan format HH:mm:ss\nContoh: 08:00:00",
                "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Cek ID sudah dipakai atau belum
        if (controllerShift.getById(id) != null) {
            JOptionPane.showMessageDialog(this,
                "ID " + id + " sudah digunakan! Gunakan ID lain.",
                "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Simpan ke database
        Shift s = new Shift(id, inputNama, inputJamMasuk);
        boolean berhasil = controllerShift.tambah(s);

        if (berhasil) {
            JOptionPane.showMessageDialog(this,
                "Shift berhasil ditambahkan!",
                "Berhasil", JOptionPane.INFORMATION_MESSAGE);
            bersihkanField();
            refreshTabel();
        } else {
            JOptionPane.showMessageDialog(this,
                "Gagal menambahkan shift!",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tambahBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        String inputId       = idTF.getText().trim();
        String inputNama     = namaTF.getText().trim();
        String inputJamMasuk = jamTF.getText().trim();

        // Validasi kosong
        if (inputId.isEmpty() || inputNama.isEmpty() || inputJamMasuk.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Pilih dulu data dari tabel sebelum update!",
                "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validasi ID harus angka
        int id;
        try {
            id = Integer.parseInt(inputId);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "ID tidak valid!",
                "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validasi format jam
        if (!inputJamMasuk.matches("^([01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d$")) {
            JOptionPane.showMessageDialog(this,
                "Format jam masuk salah!\nGunakan format HH:mm:ss\nContoh: 14:00:00",
                "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Konfirmasi sebelum update
        int konfirmasi = JOptionPane.showConfirmDialog(this,
            "Yakin ingin mengupdate shift ID " + id + "?",
            "Konfirmasi Update", JOptionPane.YES_NO_OPTION);

        if (konfirmasi == JOptionPane.YES_OPTION) {
            Shift s = new Shift(id, inputNama, inputJamMasuk);
            boolean berhasil = controllerShift.update(s);

            if (berhasil) {
                JOptionPane.showMessageDialog(this,
                    "Data shift berhasil diupdate!",
                    "Berhasil", JOptionPane.INFORMATION_MESSAGE);
                bersihkanField();
                refreshTabel();
            } else {
                JOptionPane.showMessageDialog(this,
                    "Gagal mengupdate data shift!",
                    "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void hapusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBtnActionPerformed

        String inputId = idTF.getText().trim();

        if (inputId.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Pilih dulu data dari tabel sebelum hapus!",
                "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int id;
        try {
            id = Integer.parseInt(inputId);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "ID tidak valid!",
                "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Konfirmasi sebelum hapus
        int konfirmasi = JOptionPane.showConfirmDialog(this,
            "Yakin ingin menghapus shift ID " + id + "?\n"
            + "Data absensi yang menggunakan shift ini juga akan terpengaruh!",
            "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);

        if (konfirmasi == JOptionPane.YES_OPTION) {
            boolean berhasil = controllerShift.hapus(id);

            if (berhasil) {
                JOptionPane.showMessageDialog(this,
                    "Shift berhasil dihapus!",
                    "Berhasil", JOptionPane.INFORMATION_MESSAGE);
                bersihkanField();
                refreshTabel();
            } else {
                JOptionPane.showMessageDialog(this,
                    "Gagal menghapus shift!\n"
                    + "Kemungkinan shift ini masih digunakan di data absensi.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_hapusBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        bersihkanField();
        cariNamaTF.setText("");
        refreshTabel();
        JOptionPane.showMessageDialog(this,
            "Data berhasil di-refresh!",
            "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void cariBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariBtnActionPerformed
        String keyword = cariNamaTF.getText().trim();

        if (keyword.isEmpty()) {
            refreshTabel();
            return;
        }

        // Filter dari list berdasarkan nama shift
        List<Shift> semua = controllerShift.getAll();
        List<Shift> hasil = new java.util.ArrayList<>();

        for (Shift s : semua) {
            if (s.getNama_shift().toLowerCase().contains(keyword.toLowerCase())) {
                hasil.add(s);
            }
        }

        if (hasil.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Shift dengan nama \"" + keyword + "\" tidak ditemukan!",
                "Info", JOptionPane.INFORMATION_MESSAGE);
            refreshTabel();
        } else {
            tableModel = new TableModelShift(hasil);
            jTable1.setModel(tableModel);
        }
    }//GEN-LAST:event_cariBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        new FormDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void bersihkanField() {
        idTF.setText("");
        namaTF.setText("");
        jamTF.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormShift().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton cariBtn;
    private javax.swing.JLabel cariLabel;
    private javax.swing.JTextField cariNamaTF;
    private javax.swing.JButton hapusBtn;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jamLabel;
    private javax.swing.JTextField jamTF;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JTextField namaTF;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton tambahBtn;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
